apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: plex-route
  namespace: plex
spec:
  parentRefs:
    - name: kraken-gateway
      sectionName: plex-https
      namespace: kraken
  hostnames:
    - "plex.kraken-plugins.com"
  rules:
    - backendRefs:
        - name: plex-service
          port: 32400
      timeouts:
        request: 3600s