apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: spotify-plex-sync-route
  namespace: plex
spec:
  parentRefs:
    - name: kraken-gateway
      sectionName: plex-sync-https
  hostnames:
    - "plex-sync.kraken-plugins.com"
  rules:
    - backendRefs:
        - name: spotify-plex-sync-svc
          port: 8000
      timeouts:
        request: 3600s